src/Blockcore.Explorer/Controllers/BlockExplorerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Blockcore.Explorer.Models;
using Blockcore.Explorer.Models.ApiModels;
using Blockcore.Explorer.Services;
using Blockcore.Explorer.Settings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using RestSharp;

namespace Blockcore.Explorer.Controllers
{
   [ApiExplorerSettings(IgnoreApi = true)]
   [Route("block-explorer")]
   public class BlockExplorerController : Controller
   {
      private readonly ExplorerSettings settings;
      private readonly ChainSettings chainSettings;
      private readonly IMemoryCache memoryCache;
      private readonly Status stats;
      private readonly BlockIndexService indexService;

      public BlockExplorerController(IMemoryCache memoryCache,
          BlockIndexService indexService,
          IOptions<ExplorerSettings> settings,
          IOptions<ChainSettings> chainSettings)
      {
         this.memoryCache = memoryCache;

         if (this.memoryCache.Get("BlockchainStats") != null)
         {
            stats = JsonConvert.DeserializeObject<Status>(this.memoryCache.Get("BlockchainStats").ToString());
         }
         else
         {
            stats = new Status { Error = "BlockchainStats not available yet." };
         }

         this.indexService = indexService;
         this.settings = settings.Value;
         this.chainSettings = chainSettings.Value;
      }

      [HttpGet]
      public IActionResult Index()
      {
         ViewBag.Features = settings.Features;
         ViewBag.Setup = settings.Setup;
         ViewBag.Chain = chainSettings;

         try
         {
            BlockModel latestBlock = indexService.GetLatestBlock();

            ViewBag.LatestBlock = latestBlock;
            ViewBag.BlockchainHeight = latestBlock.BlockIndex;

            var latestBlocks = new List<dynamic>();
            latestBlocks.Add(latestBlock);

            for (int i = (int)ViewBag.LatestBlock.BlockIndex - 1; i >= (int)ViewBag.LatestBlock.BlockIndex - 5; i--)
            {
               latestBlocks.Add(indexService.GetBlockByHeight(i));
            }

            ViewBag.Blocks = latestBlocks;

            return View();
         }
         catch (Exception ex)
         {
            ViewBag.Error = ex;
            return View();
         }
      }

      [HttpGet, HttpPost]
      [Route("search")]
      public IActionResult Search(SearchBlockExplorer searchBlockExplorer)
      {
         ViewBag.Features = settings.Features;
         ViewBag.Setup = settings.Setup;
         ViewBag.Chain = chainSettings;

         if (searchBlockExplorer.Query == null)
         {
            return RedirectToAction("Index");
         }
         else if (searchBlockExplorer.Query.Length == 34)
         {
            return RedirectToAction("Address", new { address = searchBlockExplorer.Query });
         }
         else if (searchBlockExplorer.Query.Length == 64)
         {
            return RedirectToAction("Transaction", new { transactionId = searchBlockExplorer.Query });
         }
         else if (searchBlockExplorer.Query.Length <= 8)
         {
            return RedirectToAction("Block", new { block = searchBlockExplorer.Query });
         }

         return RedirectToAction("Index");
      }

      [HttpGet]
      [Route("block/{block}")]
      public IActionResult Block(string block)
      {
         ViewBag.Features = settings.Features;
         ViewBag.Setup = settings.Setup;
         ViewBag.Chain = chainSettings;

         ViewBag.BlockchainHeight = stats.SyncBlockIndex;

         BlockModel result = (block.ToLower() == "latest") ? indexService.GetLatestBlock() : indexService.GetBlockByHeight(int.Parse(block));
         return View(result);
      }

      [HttpGet]
      [Route("block/hash/{hash}")]
      public IActionResult BlockHash(string hash)
      {
         ViewBag.Features = settings.Features;
         ViewBag.Setup = settings.Setup;
         ViewBag.Chain = chainSettings;

         ViewBag.BlockchainHeight = stats.SyncBlockIndex;
         BlockModel block = indexService.GetBlockByHash(hash);
         return View("Block", block);
      }

      [HttpGet]
      [Route("address/{address}")]
      public IActionResult Address(string address)
      {
         ViewBag.Features = settings.Features;
         ViewBag.Setup = settings.Setup;
         ViewBag.Chain = chainSettings;

         ViewBag.BlockchainHeight = stats.SyncBlockIndex;

         return View(indexService.GetTransactionsByAddress(address));
      }

      [HttpGet]
      [Route("transaction/{transactionId}")]
      public IActionResult Transaction(string transactionId)
      {
         ViewBag.Features = settings.Features;
         ViewBag.Setup = settings.Setup;
         ViewBag.Chain = chainSettings;

         ViewBag.BlockchainHeight = stats.SyncBlockIndex;

         TransactionDetailsModel trx = indexService.GetTransaction(transactionId);

         if (trx != null && trx.TransactionId == null)
         {
            return RedirectToAction("BlockHash", new { hash = transactionId });
         }

         if (trx.IsCoinbase)
         {
            ViewBag.TransactionType = "Coinbase";
         }
         else if (trx.IsCoinstake && trx.Outputs.Exists(o => o.OutputType == "TX_PUBKEY"))
         {
            ViewBag.TransactionType = "Stake Reward";
         }
         // Make a prediction if this is a cold stake activation transaction or a cold stake reward.
         else if (trx.IsCoinstake && trx.Outputs.Exists(o => o.OutputType == "TX_COLDSTAKE"))
         {
            ViewBag.TransactionType = "Cold Stake Reward";
         }
         else if (!trx.IsCoinstake && trx.Outputs.Exists(o => o.OutputType == "TX_COLDSTAKE"))
         {
            ViewBag.TransactionType = "Cold Stake Activation";
         }
         // This prediction can be greatly improved when we can parse the script of input, which should clearly show us this is cold stake rewards.
         else if (!trx.IsCoinstake && !trx.IsCoinbase && trx.Outputs.Count == 1 && trx.Inputs.GroupBy(z => z.InputTransactionId).Any(z => z.Count() > 1))
         {
            ViewBag.transactionType = "Cold Stake Withdraw";
         }
         else
         {
            ViewBag.TransactionType = "Normal";
         }

         return View(trx);
      }
   }
}

src/Blockcore.Explorer/Controllers/NetworkController.cs
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using Blockcore.Explorer.Models;
using Blockcore.Explorer.Services;
using Blockcore.Explorer.Settings;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using QRCoder;

namespace Blockcore.Explorer.Controllers
{
   [ApiExplorerSettings(IgnoreApi = true)]
   public class NetworkController : Controller
   {
      private readonly IMemoryCache memoryCache;
      private readonly TickerService tickerService;
      private readonly WeightService weightService;
      private readonly CurrencyService currencyService;
      private readonly ExplorerSettings settings;
      private readonly ChainSettings chainSettings;
      private readonly ILogger<HomeController> log;
      private readonly BlockIndexService indexService;

      public NetworkController(IMemoryCache memoryCache,
          ILogger<HomeController> log,
          TickerService tickerService,
          BlockIndexService indexService,
          WeightService weightService,
          CurrencyService currencyService,
          IOptions<ExplorerSettings> settings,
          IOptions<ChainSettings> chainSettings)
      {
         this.memoryCache = memoryCache;
         this.log = log;
         this.indexService = indexService;
         this.settings = settings.Value;
         this.chainSettings = chainSettings.Value;
         this.tickerService = tickerService;
         this.weightService = weightService;
         this.currencyService = currencyService;
      }

      public IActionResult Index()
      {
         if (!settings.Features.Home)
         {
            return Redirect("/block-explorer");
         }

         ViewBag.Features = settings.Features;
         ViewBag.Setup = settings.Setup;
         ViewBag.Chain = chainSettings;
         ViewBag.Ticker = settings.Ticker;
         
         ViewBag.Url = Request.Host.ToString();

         Models.ApiModels.CoinInfo nodeInfo = indexService.GetNodeInfo();
         ViewBag.Peers = indexService.GetPeers(DateTime.UtcNow);

         return View(nodeInfo);
      }
   }
}

src/Blockcore.Explorer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>@ViewBag.Title | @ViewBag.Setup.Title</title>
   <meta name="Content-Language" content="en">
   <meta name="Description" content="@(ViewBag.Description ?? $"{ViewBag.Setup.Title} is a simple and free ${ViewBag.Chain.Symbol} ticker.")">
   <meta name="Keywords" content="bitcoin,cryptos,cryptocurrencies,coins,$@ViewBag.Chain.Symbol,ticker,explorer,block explorer">
   <link rel="icon" type="image/png" href="/favicon">
   <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">
   <link href="~/css/all.css?v2" rel="stylesheet" type="text/css">
   <environment include="Development">
      <link href="~/css/default.css" rel="stylesheet" type="text/css">
   </environment>
   <environment exclude="Development">
      <link href="~/css/default.min.css" rel="stylesheet" type="text/css">
   </environment>
   <link href="~/css/explorer.css" rel="stylesheet" type="text/css">
   @RenderSection("Style", false)
</head>
<body>
    <header class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <a asp-controller="Home" asp-action="Index" class="logo ">
                            @if (!string.IsNullOrWhiteSpace(ViewBag.Chain.Icon))
                            {
                                <img src="@ViewBag.Chain.Icon" class="" alt="@ViewBag.Setup.Title" />
                            }
                            else
                            {
                                <img src="~/images/logo.png" class="" alt="@ViewBag.Setup.Title" />
                            }
                            <span class="text-white">@ViewBag.Setup.Title</span> <span class="text-info text-hide">v2</span>

                        </a>
                        <ul class="nav">
                           @if (ViewBag.Features.Home)
                           {
                              <li class="@(Context.Request.Path.Equals(Url.Action("Index", "Home")) ? "active":"")"><a asp-action="Index" asp-controller="Home"><i class="fa fa-home"></i> HOME</a></li>
                           }

                           @if (ViewBag.Features.Explorer)
                           {
                              <li class="@(Context.Request.Path.Equals(Url.Action("Index", "BlockExplorer")) ? "active":"")"><a asp-action="Index" asp-controller="BlockExplorer"><i class="fa fa-cube"></i> BLOCK EXPLORER</a></li>
                           }

                           @if (ViewBag.Features.Network)
                           {
                              <li class="@(Context.Request.Path.Equals(Url.Action("Index", "Network")) ? "active":"")"><a asp-action="Index" asp-controller="Network"><i class="fas fa-project-diagram"></i> NETWORK</a></li>
                           }

                           @if (ViewBag.Features.API)
                           {
                              <li><a href="@ViewBag.Setup.DocumentationUrl"><i class="fa fa-book"></i> API</a></li>
                           }

                           @if (ViewBag.Features.About)
                           {
                              <li class="@(Context.Request.Path.Equals(Url.Action("About", "Home")) ? "active":"")"><a asp-action="About" asp-controller="Home"><i class="fa fa-info-circle"></i> ABOUT</a></li>
                           }
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    @RenderBody()


    @if (ViewBag.Features.Footer)
    {
        @if (string.IsNullOrWhiteSpace(ViewBag.Setup.Footer))
        {
            <div id="crafted">
                <p class="text-center small">Blockcore Explorer - <a href="https://www.blockcore.net/">www.blockcore.net</a></p>
            </div>
        }
        else
        {
            <div id="crafted">
                <p class="text-center small">@ViewBag.Setup.Footer</p>
            </div>
        }
    }

    <script src="~/js/jquery-2.1.0.min.js"></script>
    <script src="~/js/popper.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/particles.min.js"></script>
    <script src="~/js/scrollreveal.min.js"></script>
    <script src="~/js/jquery.downCount.js"></script>
    <script src="~/js/parallax.min.js"></script>
    <script src="~/js/particle-green.js"></script>
    <environment include="Development">
        <script src="~/js/default.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/default.min.js"></script>
    </environment>
    @RenderSection("Scripts", false)
</body>

</html>